### ISSUE TITLE
Heads-up: UB due to misuse of mem::uninitialized will soon lead to panic

### ISSUE THREAD

**Issue by RalfJung** [49nord/utimeseries-rs#7]
[Here](https://github.com/49nord/utimeseries-rs/blob/535b1f4f63cdf5604b4abf394702d64d8302b10e/src/util.rs#L105), this crate causes UB by ["Producing an invalid value"](https://doc.rust-lang.org/reference/behavior-considered-undefined.html). Concretely, it produces a value of an arbitrary  type `T` with `mem::uninitialized()`. In the near future the call to `mem::uninitialized()` [will panic to avoid UB](https://github.com/rust-lang/rust/pull/66059), and [our crater run](https://github.com/rust-lang/rust/pull/66059#issuecomment-575164263) determined that this crate will be affected.

`mem::uninitialized()` is deprecated since Rust 1.39. The intended replacement is [`MaybeUninit`](https://doc.rust-lang.org/core/mem/union.MaybeUninit.html), which tracks the possibility of uninitialized values at the type level to make sure the compiler does not make any false assumptions.

**Comment by mbr** [comment]
Thanks. Fix released as `0.1.1`.
